---
title: "Breakdowns_model"
author: "Céline Guex"
date: "13/12/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(ggplot2)
library('lme4')
```

```{r loading-data}
load("Data/Breakdowns.RData")
```

# A bit of data exploration
add plots to justify choices
```{r visu-y}
ggplot(Breakdowns, aes(x=Breakdowns))+
  geom_histogram(aes(y=..density..), alpha=0.4, position="identity", lwd=0.1)+
  geom_density(alpha=0.3, lwd=1)+
  ggtitle("Repartition of y")
```


# First models

```{r sel1}
fullmodel <- glm(Breakdowns ~ log10(Traffic)+ log10(Length) + HGV + Slope + as.factor(Limit) + as.factor(Direction) + as.factor(Urban) + as.factor(Type) + as.factor(Year) + as.factor(SlopeType), family="poisson", data=Breakdowns)
model <- step(fullmodel, direction = 'backward')

emptymodel <- glm(Breakdowns ~ log10(Traffic)  ,family="poisson", data=Breakdowns)
model <- step(emptymodel, direction = 'forward')

```

# Models with fixed and random effects

<!-- *Random effects* -->
<!-- The idea here would be to consider random and fixed effects on the variables that were significant previously :\ -->
<!--   *random : Tunnel, Company,  -->
<!--   *fixed : log(Traffic) + HGV + Urban + Type + log(Length) + Limit + SlopeType + Width\ -->

First, we put Tunnel as the random effect
  
```{r Mixed model tunnel, echo=FALSE}
summary(glmer(Breakdowns ~ log10(Traffic) + HGV + log10(Length) + (1 | Tunnel ), data = Breakdowns, family=poisson))
``` 
Then with company
```{r Mixed model company, echo=FALSE}
summary(glmer(Breakdowns ~ log10(Traffic) + HGV + log10(Length) + (1 | Company ), data = Breakdowns, family=poisson))
``` 


```{r Mixed model company and tunnel, echo=FALSE}
library("lme4")
mixed_model <- glmer(Breakdowns ~ log10(Traffic) + HGV + log10(Length) + (1 | Company) +(1| Tunnel), data = Breakdowns, family=poisson)
summary(mixed_model)
```

